const express=require('express'); const path=require('path'); const fs=require('fs'); const crypto=require('crypto');
const app=express(); app.use(express.json({limit:'10mb'})); app.use(express.static(path.join(__dirname,'public')));
const DB=path.join(__dirname,'data.json');
function load(){let db;try{db=JSON.parse(fs.readFileSync(DB,'utf8'))}catch{db={users:[],codes:[],planRequests:[],payments:[]}};db.users||=[];db.codes||=[];db.planRequests||=[];db.payments||=[];expirePlans(db);return db}
function expirePlans(db){const now=Date.now();for(const u of (db.users||[])){if(u.plan&&u.planExpires&&new Date(u.planExpires).getTime()<=now){u.planStatus='expired'}else if(u.plan){u.planStatus='active'}else{u.planStatus='none'}}}
function hasActivePlan(u){return !!(u&&u.plan&&u.planExpires&&new Date(u.planExpires).getTime()>Date.now())}
function requireActivePlan(req,res,next){const db=load();const u=db.users.find(x=>x.id===req.session.userId);if(!hasActivePlan(u))return res.status(402).json({error:'Tu plan ha vencido. Renueva tu plan para continuar utilizando las herramientas de THIAGO IA.',code:'PLAN_EXPIRED'});req.user=u;next()}
function save(db){fs.writeFileSync(DB,JSON.stringify(db,null,2))}
const plans={basic:{name:'BÁSICO',price:85},pro:{name:'PRO',price:160},business:{name:'NEGOCIO',price:255}};
const adminKey=()=>process.env.ADMIN_KEY||'THIAGO2026';
function token(){return crypto.randomBytes(24).toString('hex')}
const sessions=new Map(); function auth(req,res,next){const t=(req.headers.authorization||'').replace('Bearer ',''); const s=sessions.get(t); if(!s)return res.status(401).json({error:'Sesión no válida'}); req.session=s;next()}
app.get('/api/plans',(req,res)=>res.json(plans));
app.post('/api/access/request',(req,res)=>{let {email,name='',phone=''}=req.body; email=(email||'').trim().toLowerCase(); if(!email)return res.status(400).json({error:'Correo requerido'}); const db=load(); let u=db.users.find(x=>x.email===email); if(!u){if(!name.trim())return res.json({needsRegistration:true}); u={id:crypto.randomUUID(),email,name:name.trim(),phone:phone.trim(),plan:null,planExpires:null,status:'active',createdAt:new Date().toISOString()}; db.users.push(u)} const code=String(Math.floor(100000+Math.random()*900000)); db.codes=db.codes.filter(x=>x.email!==email||x.used); db.codes.push({id:crypto.randomUUID(),email,code,expiresAt:Date.now()+10*60*1000,used:false,createdAt:new Date().toISOString()}); save(db); res.json({ok:true,email,expiresIn:600,message:'Código generado. Solicítalo al administrador.'})});
app.post('/api/access/verify',(req,res)=>{const email=(req.body.email||'').trim().toLowerCase(), code=String(req.body.code||''); const db=load(); const c=[...db.codes].reverse().find(x=>x.email===email&&!x.used&&x.code===code); if(!c||c.expiresAt<Date.now())return res.status(400).json({error:'Código incorrecto o vencido'}); c.used=true; const u=db.users.find(x=>x.email===email); save(db); const t=token(); sessions.set(t,{role:'client',userId:u.id,email}); res.json({token:t,user:u})});
app.post('/api/admin/login',(req,res)=>{if(req.body.key!==adminKey())return res.status(401).json({error:'Clave incorrecta'}); const t=token();sessions.set(t,{role:'admin'});res.json({token:t})});
app.get('/api/me',auth,(req,res)=>{if(req.session.role==='admin')return res.json({role:'admin'}); const u=load().users.find(x=>x.id===req.session.userId);res.json({role:'client',user:u})});
app.post('/api/logout',auth,(req,res)=>{const t=(req.headers.authorization||'').replace('Bearer ','');sessions.delete(t);res.json({ok:true})});
app.get('/api/admin/dashboard',auth,(req,res)=>{if(req.session.role!=='admin')return res.sendStatus(403); const db=load();res.json({users:db.users,codes:db.codes.filter(x=>!x.used&&x.expiresAt>Date.now()),planRequests:db.planRequests,payments:db.payments,plans})});
app.post('/api/plans/request',auth,(req,res)=>{if(req.session.role!=='client')return res.sendStatus(403); if(!plans[req.body.plan])return res.status(400).json({error:'Plan inválido'}); const db=load(); const u=db.users.find(x=>x.id===req.session.userId); const kind=!hasActivePlan(u)&&u.plan?'renewal':'plan'; const pending=db.planRequests.find(x=>x.userId===u.id&&x.status==='pending');if(pending)return res.status(409).json({error:'Ya tienes una solicitud pendiente de aprobación.'}); db.planRequests.push({id:crypto.randomUUID(),userId:u.id,email:u.email,currentPlan:u.plan,requestedPlan:req.body.plan,kind,status:'pending',createdAt:new Date().toISOString()});save(db);res.json({ok:true,kind})});
app.post('/api/admin/plan-request/:id',auth,(req,res)=>{if(req.session.role!=='admin')return res.sendStatus(403); const db=load(), r=db.planRequests.find(x=>x.id===req.params.id); if(!r)return res.sendStatus(404); r.status=req.body.action==='approve'?'approved':'rejected'; if(r.status==='approved'){const u=db.users.find(x=>x.id===r.userId);u.plan=r.requestedPlan;u.planExpires=new Date(Date.now()+30*86400000).toISOString();u.planStatus='active'} save(db);res.json({ok:true})});
app.post('/api/chat',auth,requireActivePlan,async(req,res)=>{if(req.session.role!=='client')return res.sendStatus(403);try{const OpenAI=require('openai');const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});const content=[{type:'input_text',text:String(req.body.message||'Analiza el archivo adjunto.')}];for(const a of (req.body.attachments||[]).slice(0,4)){if(!a.data)continue;if(String(a.type).startsWith('image/'))content.push({type:'input_image',image_url:a.data});else content.push({type:'input_file',filename:a.name||'archivo',file_data:a.data});}const response=await client.responses.create({model:process.env.OPENAI_MODEL||'gpt-5.4',input:[{role:'user',content}]});res.json({text:response.output_text||'Sin respuesta'})}catch(e){res.status(500).json({error:e.message||'Error de IA'})}});
app.post('/api/image',auth,requireActivePlan,async(req,res)=>{if(req.session.role!=='client')return res.sendStatus(403);try{const prompt=String(req.body.prompt||'').trim();if(!prompt)return res.status(400).json({error:'Descripción requerida'});const OpenAI=require('openai');const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});const out=await client.images.generate({model:process.env.OPENAI_IMAGE_MODEL||'gpt-image-1',prompt,size:'1024x1024'});const b64=out.data&&out.data[0]&&out.data[0].b64_json;if(!b64)return res.status(500).json({error:'No se recibió la imagen'});res.json({image:'data:image/png;base64,'+b64})}catch(e){res.status(500).json({error:e.message||'Error generando imagen'})}});
app.get('/*splat',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
app.listen(process.env.PORT||3000,()=>console.log('THIAGO IA V30 disponible'));
